services:
  beszel-agent:
    healthcheck:
      test:
        - CMD
        - /agent
        - health
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
      - CAP_PERFMON
    container_name: beszel-agent
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/nvme0:/dev/nvme0
      - /dev/mmcblk0:/dev/mmcblk0
      - /dev/dri/card0:/dev/dri/card0
    environment:
      - HUB_URL=http://pi-server.internal:8090
      - KEY=your-server-key
      - LISTEN=45876
      - TOKEN=your-token
      - GPU_COLLECTOR=intel_gpu_top
    image: henrygd/beszel-agent-intel
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
      - /media/nvme0n1p1/AppData/beszel_agent_data:/var/lib/beszel-agent
      - /media/Quick-Storage/.beszel:/extra-filesystems/md0__Quick-Storage:ro
    network_mode: host
networks:
  default:
    name: beszel-agent_default