services:
  beszel-agent:
    healthcheck:
      test:
        - CMD
        - /agent
        - health
      interval: 120s
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
      - ./beszel_agent_data:/var/lib/beszel-agent
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro  (1)
    environment:
      LISTEN: 45876
      KEY: your-server-key
      TOKEN: your-token
      HUB_URL: http://pi-server.internal:8090