services:
  cloudflared:
    container_name: cloudflare-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    networks:
      - it-tools_default
      - beszel_default
    environment:
      - TUNNEL_TOKEN=your_token_string_here

networks:
  it-tools_default:
    external: true
  beszel_default:
    external: true