services:
  cloudflared:
    container_name: cloudflared
    image: wisdomsky/cloudflared-web:latest
    restart: unless-stopped
    privileged: false
    network_mode: host
    ports:
      - target: 14333
        published: "14333"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/casaos-cloudflared/config
        target: /config