services:
  dockge:
    container_name: dockge
    image: louislam/dockge:1
    restart: unless-stopped
    privileged: false
    networks:
      - default
    ports:
      - mode: ingress
        target: 5001
        published: "5001"
        protocol: tcp
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: true
      - type: bind
        source: /DATA/AppData/dockge/data
        target: /app/data
        bind:
          create_host_path: true
      - type: bind
        source: /DATA/AppData/dockge/stacks
        target: /DATA/AppData/dockge/stacks
        bind:
          create_host_path: true
    environment:
      - DOCKGE_STACKS_DIR=/DATA/AppData/dockge/stacks

networks:
  default:
    name: big-bear-dockge_default