services:
  server:
    container_name: gitea
    image: docker.gitea.com/gitea:latest
    restart: always
    networks:
      - gitea
    ports:
      - "3080:3000"
      - "222:22"
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000

  runner:
    container_name: gitea_runner
    image: gitea/act_runner:latest
    restart: always
    volumes:
      - ./runner-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GITEA_INSTANCE_URL=http://192.168.50.4:3080
      - GITEA_RUNNER_REGISTRATION_TOKEN=<your_token_here>

networks:
  gitea:
    external: false