services:
  glances:
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    cpu_shares: 90
    container_name: glances
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/nvme0:/dev/nvme0
      - /dev/md0:/dev/md0
      - /dev/mmcblk0:/dev/mmcblk0
    environment:
      - GLANCES_OPT=-C /glances/conf/glances.conf -w --enable-plugin smart
      - TZ=America/New_York
    image: nicolargo/glances:latest-full
    pid: host
    ports:
      - target: 61208
        published: "61208"
        protocol: tcp
      - target: 61209
        published: "61209"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /mnt
        target: /mnt
      - type: bind
        source: /etc/os-release
        target: /etc/os-release
      - type: bind
        source: /media/nvme0n1p1/AppData/glances/glances.conf
        target: /glances/conf/glances.conf
      - type: bind
        source: /media/Quick-Storage
        target: /media/Quick-Storage
      - type: bind
        source: /media/nvme0n1p1
        target: /media/nvme0n1p1
      - type: bind
        source: /media/ZimaOS-HD
        target: /media/ZimaOS-HD