services:
  glances:
    container_name: glances
    image: nicolargo/glances:latest-full  # (1)!
    restart: always
    privileged: false
    pid: host
    network_mode: host
    read_only: true
    volumes:
      - /:/rootfs:ro
      - /mnt/usb-drive:/mnt/usb-drive:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./glances.conf:/glances/conf/glances.conf
      - /etc/os-release:/etc/os-release:ro
    tmpfs:
      - /tmp
    environment:
      - TZ=America/New_York  # (2)!
      - GLANCES_OPT=-C /glances/conf/glances.conf -w --enable-plugin smart
      - PYTHONPYCACHEPREFIX=/tmp/py_caches