services:
  gotify:
    container_name: gotify
    image: gotify/server:latest
    restart: unless-stopped
    ports:
      - "8180:80"
    volumes:
      - ./data:/app/data
    environment:
      - GOTIFY_DEFAULTUSER_PASS=ChangeThisPassword123  # (1)!
      - TZ=America/New_York