services:
  immich_frame:  # (1)!
    container_name: immich_frame
    image: ghcr.io/immichframe/immichframe:latest
    restart: always
    ports:
      - 8081:8080
    environment:
      - IMMICH_URL=http://<ZIMABOARD_IP>:2283
      - API_KEY=<YOUR_IMMICH_API_KEY_FOR_FRAME>
      - SLIDESHOW_DURATION=60
      - SHOW_CLOCK=true
      - SHOW_WEATHER=true
      - WEATHER_LOCATION=Reisterstown, MD
      - ALBUM_UIDS=<UUID_OF_NESTHUB_ALBUM>  # (2)!

  immich_auto_album:  # (3)!
    container_name: immich_auto_album
    image: ghcr.io/alangrainger/immich-person-to-album:latest
    restart: always
    volumes:
      - ./config.json:/app/config.json
    environment:
      - IMMICH_URL=http://<ZIMABOARD_IP>:2283
      - API_KEY=<YOUR_IMMICH_API_KEY_FOR_SYNC>
      - SYNC_MODE=1  # (4)!