services:
  it-tools:
    container_name: it-tools
    image: sharevb/it-tools:latest
    pull_policy: always
    restart: unless-stopped
    networks:
      - it-tools_default
    ports:
      - 8080:8080
    dns:
      - 192.168.50.2
      - 192.168.50.6

  network-utils-ws:
    container_name: network-utils-ws
    image: sharevb/network-utils-ws:latest
    restart: unless-stopped
    networks:
      - it-tools_default
    ports:
      - 8000:8000

networks:
  it-tools_default:
    external: true
