services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:32.0
    restart: unless-stopped
    privileged: false
    network_mode: bridge
    ports:
      - target: 80
        published: "10081"
        protocol: tcp
      - target: 443
        published: "10443"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/nextcloud/var/www/html
        target: /var/www/html