services:
  ntopng:
    container_name: ntop
    hostname: ntop
    image: ntop/ntopng:latest
    restart: always
    depends_on:
      - clickhouse
    network_mode: host
    volumes:
      - ntopng_redis:/var/lib/redis
    # (1)!
    command: [ '-i', 'eth0', '-i', 'eth1', '-i', 'tcp://*:5556c', '-F', 'clickhouse', '--disable-login', '1', '--community' ]

  clickhouse:
    container_name: clickhouse
    hostname: clickhouse
    image: clickhouse/clickhouse-server:latest
    restart: always
    network_mode: host
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server

volumes:
  clickhouse_data:
  clickhouse_logs:
  ntopng_redis: