services:
  app:
    cpu_shares: 90
    container_name: obsidian-livesync
    environment:
      - COUCHDB_PASSWORD=password  # (1)!
      - COUCHDB_USER=bhaube
    image: couchdb:3.5.0
    ports:
      - mode: ingress
        target: 5984
        published: "5984"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/big-bear-obsidian-livesync/data/couchdb
        target: /opt/couchdb/data
        bind:
          create_host_path: true
      - type: bind
        source: /DATA/AppData/big-bear-obsidian-livesync/data/local.ini
        target: /opt/couchdb/etc/local.ini
        bind:
          create_host_path: true