services:
  portracker:
    container_name: portracker
    image: mostafawahied/portracker:latest
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    ports:
      - mode: ingress
        target: 4999
        published: "4999"
        protocol: tcp
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CACHE_TIMEOUT_MS=30000
      - DATABASE_PATH=/data/portracker.db
      - DEBUG=false
      - DISABLE_CACHE=false
      - INCLUDE_UDP=true
      - PORT=4999
      - TRUSTED_LOCAL_EMAIL=server@haube-pereira.com