services:
  app:
    cpu_shares: 90
    container_name: spoolman
    environment:
      - SPOOLMAN_AUTOMATIC_BACKUP=TRUE
      - SPOOLMAN_DB_TYPE=sqlite
      - SPOOLMAN_LOGGING_LEVEL=INFO
      - TZ=America/New_York
    image: ghcr.io/donkie/spoolman:latest
    ports:
      - mode: ingress
        target: 8000
        published: "7912"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/big-bear-spoolman/data
        target: /home/app/.local/share/spoolman
        bind:
          create_host_path: true