services:
  spoolman:
    image: ghcr.io/donkie/spoolman:latest # (1)!
    restart: unless-stopped
    volumes:
      # (2)!
      - type: bind
        source: ./data
        target: /home/app/.local/share/spoolman # (3)!
    ports:
      # (4)!
      - "7912:8000"
    environment:
      - TZ=America/New_York # (5)!
      - SPOOLMAN_AUTOMATIC_BACKUP=true
      - SPOOLMAN_DB_TYPE=sqlite
      - SPOOLMAN_LOGGING_LEVEL=info
      - SPOOLMAN_CORS_ORIGIN=http://kacey.internal,http://kacey.internal:4408
