services:
  syncthing:
    cpu_shares: 90
    container_name: syncthing
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/New_York
    image: linuxserver/syncthing:latest
    ports:
      - target: 8384
        published: "8384"
        protocol: tcp
      - target: 22000
        published: "22000"
        protocol: tcp
      - target: 22000
        published: "22000"
        protocol: udp
      - target: 21027
        published: "21027"
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/syncthing/config
        target: /config
      - type: bind
        source: /DATA
        target: /DATA