services:
  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - target: 8384
        published: "8384"
        protocol: tcp
      - target: 22000
        published: "22000"
        protocol: tcp
      - target: 22000
        published: "22000"
        protocol: udp
      - target: 21027
        published: "21027"
        protocol: udp
    volumes:
      - /media/nvme0n1p1/AppData/syncthing/config:/config
      - /media/Quick-Storage:/Quick-Storage
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: America/New_York