services:
  ttydbridge:
    container_name: ttydbridge
    image: cp0204/ttydbridge:v0.0.3
    restart: unless-stopped
    pid: host
    privileged: true
    network_mode: bridge    
    volumes:
      - type: bind
        source: /opt
        target: /opt
        bind:
          create_host_path: true
    environment:
      - EXEC_DIR=/opt
      - PORT=2222
      - START_COMMAND=login