[ZimaOS-HD]  
browseable = yes  
guest ok = No  
path = /media/ZimaOS-HD/  
read only = No  
recycle:repository = /media/ZimaOS-HD/.trash/smb  
recycle:keeptree = yes  
recycle:versions = yes  
veto files = /.trash/ /.zima_encrypted_folders/  
delete veto files = yes  
create mask = 0777  
directory mask = 0777  
  
[nvme0n1p1]  
browseable = yes  
guest ok = No  
path = /media/nvme0n1p1  
read only = No  
recycle:repository = /media/nvme0n1p1/.trash/smb  
recycle:keeptree = yes  
recycle:versions = yes  
veto files = /.trash/ /.zima_encrypted_folders/  
delete veto files = yes  
create mask = 0777  
directory mask = 0777  
  
[Quick-Storage]  
browseable = yes  
guest ok = No  
path = /media/Quick-Storage  
read only = No  
recycle:repository = /media/Quick-Storage/.trash/smb  
recycle:keeptree = yes  
recycle:versions = yes  
veto files = /.trash/ /.zima_encrypted_folders/  
delete veto files = yes  
create mask = 0777  
directory mask = 0777  
      
[Downloads]  
browseable = yes  
guest ok = No  
path = /media/Quick-Storage/Downloads  
read only = No  
recycle:repository = /media/Quick-Storage/.trash/smb/Downloads  
recycle:keeptree = yes  
recycle:versions = yes  
veto files = /.trash/ /.zima_encrypted_folders/  
delete veto files = yes  
create mask = 0777  
directory mask = 0777  
 
[Documents]  
browseable = yes  
guest ok = No  
path = /media/Quick-Storage/Documents  
read only = No  
recycle:repository = /media/Quick-Storage/.trash/smb/Documents  
recycle:keeptree = yes  
recycle:versions = yes  
veto files = /.trash/ /.zima_encrypted_folders/  
delete veto files = yes  
create mask = 0777  
directory mask = 0777  
  
[Backup]  
browseable = yes  
guest ok = No  
path = /media/Quick-Storage/Backup  
read only = No  
recycle:repository = /media/Quick-Storage/.trash/smb/Backup  
recycle:keeptree = yes  
recycle:versions = yes  
veto files = /.trash/ /.zima_encrypted_folders/  
delete veto files = yes  
create mask = 0777  
directory mask = 0777  
  
[Gallery]  
browseable = yes  
guest ok = No  
path = /media/Quick-Storage/Gallery  
read only = No  
recycle:repository = /media/Quick-Storage/.trash/smb/Gallery  
recycle:keeptree = yes  
recycle:versions = yes  
veto files = /.trash/ /.zima_encrypted_folders/  
delete veto files = yes  
create mask = 0777  
directory mask = 0777  
  
[Media]  
browseable = yes  
guest ok = No  
path = /media/Quick-Storage/Media  
read only = No  
recycle:repository = /media/Quick-Storage/.trash/smb/Media  
recycle:keeptree = yes  
recycle:versions = yes  
veto files = /.trash/ /.zima_encrypted_folders/  
delete veto files = yes  
create mask = 0777  
directory mask = 0777