[Quick-Storage]  
browseable = yes  
guest ok = No  
path = /media/Quick-Storage  
read only = No  
recycle:repository = /media/Quick-Storage/.trash/smb  
recycle:keeptree = yes  
recycle:versions = yes  
veto files = /.trash/ /.zima_encrypted_folders/  
delete veto files = yes  
create mask = 0777  
directory mask = 0777