[Google-Drive]
type = drive
client_id = <id>.apps.googleusercontent.com
client_secret = <secret>
scope = drive
token = {token}
auth_url = https://accounts.google.com/o/oauth2/auth
token_url = https://oauth2.googleapis.com/token
metadata_owner = failok
metadata_permissions = failok
metadata_labels = failok
env_auth = false
description = rclone
team_drive = 