[global]  
 workgroup = WORKGROUP  
 server string = pi-server %v  
 security = user  
  
[smb-share]  
 comment = Samba Share  
 path = /mnt/usb-drive/smb-share  
 browseable = yes  
 writeable = yes  
 read only = no  
 force user = admin