name: Network Documentation Portfolio
services:
    mkdocs-custom:
        stdin_open: true
        tty: true
        ports:
            - 8000:8000
        volumes:
            - ${PWD}:/docs:Z
        image: mkdocs-custom
        command: serve -a 0.0.0.0:8000
