services:
    mkdocs-custom:
        stdin_open: true
        tty: true
        volumes:
            - ${PWD}:/docs:Z
        image: mkdocs-custom
        command: build
        environment:
            - NO_MKDOCS_2_WARNING=1
