# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# --- Site Name and URL ---
site_name: Network Documentation & Portfolio
site_url: https://portfolio.rac3r4life.online

# --- Theme Settings ---
theme:
  name: material
  custom_dir: overrides
  # -- Light, Dark, and Automatic toggles --
  palette:
    # - Toggle for automatic mode -
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # - Toggle for light mode - 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # - Toggle for dark mode -
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to auto mode
  font:
    text: Google Sans Flex
    code: Google Sans Code
  # -- Icon Settings--
  icon:
    logo: material/file-document-multiple
    repo: simple/github
    # - Icons for Tags -
    tag:
      default: material/tag
      3D-printer: material/printer-3d-nozzle
      isp: material/wan
      iot: material/home-automation
      active: material/check-circle-outline
      backup: material/cloud-upload-outline
      dashboard: material/view-dashboard
      desktop: material/desktop-tower
      dns: material/dns
      docker: material/docker
      docker_host: material/docker
      domain: material/domain
      download: material/download
      file-share: material/share
      hardware: material/router-wireless
      inactive: material/close-circle-outline
      infra: material/router-network
      inventory: material/list-box-outline
      laptop: material/laptop
      living-room: material/sofa
      map: material/sitemap
      mini-rack: devices/10-inch-rack
      monitor: material/monitor-eye
      nas: material/nas
      network: material/lan 
      native: material/linux
      office: material/desk
      pc: material/desktop-classic
      print: material/printer
      printer-cart: material/printer
      remote: material/remote-desktop
      router: material/router-wireless
      server: material/server
      service: material/web
      shell: material/console
      software: material/application
      switch: material/switch
      tools: material/tools
      video: material/video
      vh: material/network-pos
      vm: material/network-pos
      vpn: material/vpn
    top: material/arrow-up-bold
    previous: material/arrow-left-bold
    next: material/arrow-right-bold
    search: material/magnify
    annotation: material/plus-circle
    edit: material/file-edit-outline
    view: material/file-code-outline
  favicon: /assets/icons/favicon.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.footer
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - content.tooltips

# --- Markdown Extensions & Settings ---
markdown_extensions:
  - attr_list
  - abbr
  - admonition
  - toc:
      permalink: true
      permalink_title: Permanent link
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.caption
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      use_pygments: true
      auto_title: false
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# --- MkDocs Native Plugins ---
plugins:
  - search
  - roamlinks
  - callouts
  - tags:
      export: true
      tags_sort_by: !!python/name:material.plugins.tags.tag_name_casefold
  - optimize
  - typeset
  - social:
      log: true
      log_level: warn
  - blog

# --- Watch directories outside of /docs --- 
watch:
  - includes

# --- Disable directory URLs ---
use_directory_urls: false

# --- Extra Settings ---
extra:
  # -- Cookies Consent Message --
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/benhaube
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/benjamin-haube/
    - icon: simple/printables
      link: https://www.printables.com/@rac3r4life
    - icon: simple/gravatar
      link: https://benhaube.link
    - icon: simple/bluesky
      link: https://bsky.app/profile/rac3r4life.me
  generator: false
  # Tag definitions for custom tag icons ^^ above ^^
  tags:
    3D-printer: 3D-printer
    ISP: isp
    IoT: iot
    active: active
    backup: backup
    dashboard: dashboard
    desktop: desktop
    dns: dns
    docker: docker
    docker_host: docker_host
    domain: domain
    download: download
    file-share: file-share
    hardware: hardware
    inactive: inactive
    infrastructure: infra
    inventory: inventory
    laptop: laptop
    living-room: living-room
    map: map
    mini-rack: mini-rack
    monitor: monitor
    nas: nas
    network: network
    native: native
    office: office
    pc: pc
    printing: print
    printer-cart: printer-cart 
    remote-access: remote
    router: router
    server: server
    service: service
    shell: shell
    software: software
    switch: switch
    tools: tools
    video: video
    virtual_host: vh 
    virtual_machine: vm 
    vpn: vpn

# --- Copyright message in site footer w/ cookies consent button ---
copyright: >
  Copyright&copy; 2026 Benjamin Haube -
  <a href="#__consent">Change cookie settings</a>

# --- Extra CSS stylesheets ---
extra_css:
  - stylesheets/extra.css

# --- Project Repository URL & Docs directory ---
repo_url: https://github.com/benhaube/network-portfolio
edit_uri: edit/main/docs/
