# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# ~~~ Site Settings ~~~

site_author: Benjamin Haube
site_name: Network Documentation & Portfolio
site_url: https://portfolio.rac3r4life.online
site_description:  My personal, self-hosted network documentation, professional portfolio, and blog website. Designed to showcase my knowledge and capabilities in IT and network security, and to make managing my homelab easier.

# Disable directory URLs
use_directory_urls: false

# Watch directories outside of '/docs'
watch:
  # 'network-documentation/includes' contains 'abbreviations.md'
  - includes

# Exclude Markdown files in '/docs/includes' from site navigation.
# The '/docs/includes' directory contains markdown files with content that will be displayed on multiple pages.
exclude_docs: |
  includes/

# Git Repo URL & Docs directory
repo_url: https://github.com/benhaube/network-portfolio
repo_name: benhaube/network-portfolio
edit_uri: edit/main/docs/

# Set the copyright message & create cookies settings link
copyright: >
  Copyright&copy; 2026 Benjamin Haube -
  <a href="#__consent">Change cookie settings</a>

# Define extra CSS / Javascript directories
extra_css:
  # Other CSS files are imported into the main 'extra.css' file.
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/mermaid.mjs
  # Tablesort is disabled for now since it didn't play nice with all of the tables on the site.
  # - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  # - assets/javascripts/tablesort.js

# ~~~ Theme Settings ~~~

theme:
  name: material
  custom_dir: overrides
  favicon: /assets/favicon.svg
  logo: /assets/favicon.svg
  
  # Theme toggles (auto/light/dark)
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: symbols/sun-moon
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light blue
      toggle:
        icon: symbols/sun
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: light blue
      toggle:
        icon: symbols/moon
        name: Switch to system preference
  
  # Set the fonts used on the site.
  font:
    text: Google Sans
    code: Google Sans Code
  
  # Enable Material for MkDocs theme features.
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.footer
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - content.tooltips
  
  # Change the icons used in the theme.
  icon:
    repo: symbols/git
    top: symbols/arrow-double-up
    previous: symbols/arrow-left
    next: symbols/arrow-right
    close: symbols/x
    search: symbols/search-lucide
    share: symbols/share-2
    annotation: symbols/code-annotation
    edit: symbols/square-pen
    view: symbols/scan-eye

    # Change icons for built-in admonitions. Custom admonitions are defined in CSS.
    admonition:
      note: symbols/attach-file
      abstract: symbols/notebook-text
      info: symbols/info
      tip: symbols/flame-outline
      success: symbols/check
      question: symbols/help
      warning: symbols/warning-outline
      failure: symbols/error-alt
      danger: symbols/electric-bolt-outline
      bug: symbols/bug-report-outline
      example: symbols/labs
      quote: symbols/quote

    # Set the icons used for page tags.
    tag:
      default: symbols/tag-outline
      3D-printer: symbols/printer-3d-nozzle-outline
      isp: symbols/web
      iot: symbols/home-automation
      active: symbols/check-circle-outline
      android: brands/android-robot
      backup: symbols/backup
      dashboard: symbols/layout-dashboard
      deprecated: symbols/trash-2
      desktop: symbols/desktop-pc-outline
      development: symbols/graph-8
      dns: symbols/dns-outline
      docker: services/docker
      docker_host: services/docker
      domain: symbols/domain
      download: symbols/download
      file-share: symbols/smb-share-outline
      hardware: symbols/devices
      inactive: symbols/circle-x
      infra: symbols/network-node
      inventory: symbols/inventory
      laptop: symbols/laptop-minimal
      linux: symbols/linux
      living-room: symbols/sofa-outline-alt
      map: symbols/graph-2
      mini-rack: symbols/10-inch-rack
      mobile: symbols/tablet-smartphone
      monitor: symbols/monitor-heart-outline
      nas: symbols/nas-outline
      native: symbols/linux
      network: symbols/lan-outline 
      new: symbols/badge-alert
      office: symbols/desk-lamp
      pc: symbols/personal-computer
      podman: services/linux-containers
      podman_host: services/linux-containers
      policy: symbols/policy
      print: symbols/print-outline
      printer-cart: symbols/print-outline
      remote: symbols/web-export
      router: symbols/router-outline
      security: symbols/security
      server: symbols/server-outline
      service: symbols/web
      shell: symbols/terminal
      software: symbols/iframe
      switch: symbols/ethernet-port-outline
      tools: symbols/construction
      tv-stand: symbols/tv
      video: symbols/movie-outline
      vh: symbols/host-outline
      vlan: symbols/hub
      vm: symbols/layers
      vpn: symbols/vpn-outline
      windows: brands/microsoft

# ~~~ Python Markdown Extensions ~~~

markdown_extensions:
  - attr_list
  - abbr
  - admonition
  - tables
  - def_list
  - footnotes
  - toc:
      permalink: true
      permalink_title: Permanent link
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path:
        - .
        - docs/includes
        - docs/assets/code
        - docs/assets/code/bash
        - docs/assets/code/config
        - docs/assets/code/gcode
        - docs/assets/code/mermaid
        - docs/assets/code/systemd
        - docs/assets/code/yaml
      auto_append:
        - includes/abbreviations.md
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.caption
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      use_pygments: true
      auto_title: false
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
          
# ~~~ MkDocs Native Plugins ~~~

plugins:
  - meta:
      enabled: true
  - search
  - open-in-new-tab:
      add_icon: false
  - awesome-nav
  - panzoom:
      full_screen: true
      always_show_hint: true 
  - tags:
      export: true
      tags_sort_by: !!python/name:material.plugins.tags.tag_name_casefold
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - optimize:
      optimize_exclude:
        - blog/*
  - social:
      log: true
      log_level: warn
      cards_layout_options:
        font_family: Google Sans Flex
  - blog:
      authors: true
      authors_file: "{blog}/.authors.yml"
      authors_profiles: true
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      post_excerpt_separator: <!-- more -->
      post_readtime_words_per_minute: 265 
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_themed: true
      auto_caption: false
      caption_position: bottom
      background: none
      shadow: true
      manual: true
  
# ~~~ Extra Settings ~~~

extra:

  # Define the text when hovering over a page status icon.
  status:
    new: Recently Added
    deprecated: Deprecated
    inactive: Inactive
  
  # Modify the cookie consent form options and message.
  consent:
    actions:
      - accept
      - reject
      - manage
    title: Cookie Consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  
  # Create the social links in the site footer.
  social:
    - icon: brands/gitlab
      link: https://gitlab.com/benhaube
      name: benhaube — Gitlab
    - icon: brands/github
      link: https://github.com/benhaube
      name: benhaube — GitHub
    - icon: brands/linkedin
      link: https://www.linkedin.com/in/benjamin-haube/
      name: Benjamin Haube — Linkedin
    - icon: brands/printables
      link: https://www.printables.com/@rac3r4life
      name: rac3r4life — Printables
    - icon: brands/reddit
      link: https://reddit.com/u/benhaube
      name: u/benhaube — Reddit
    - icon: brands/bluesky
      link: https://bsky.app/profile/rac3r4life.me
      name: rac3r4life.me — Bluesky
  
  # Disable the "Made with Material for MkDocs" message in the site footer.
  generator: false
  
  # Create / define the tags used on the site. Tag icons are set above in the 'theme > icon' section. 
  tags:
    3D-Printer: 3D-printer
    ISP: isp
    IoT: iot
    Active: active
    Android: android
    Backup: backup
    Dashboard: dashboard
    Deprecated: deprecated
    Desktop: desktop
    Development: development
    DNS: dns
    Docker: docker
    Docker Host: docker_host
    Domain: domain
    Download: download
    File Share: file-share
    Hardware: hardware
    Inactive: inactive
    Infrastructure: infra
    Inventory: inventory
    Laptop: laptop
    Linux: linux
    Living Room: living-room
    Map: map
    Mini-Rack: mini-rack
    Mobile: mobile
    Monitor: monitor
    NAS: nas
    Native: native
    Network: network
    New: new
    Office: office
    PC: pc
    Podman: podman
    Podman Host: podman_host
    Policy: policy
    Printing: print
    Printer Cart: printer-cart 
    Remote Access: remote
    Router: router
    Security: security
    Server: server
    Service: service
    Shell: shell
    Software: software
    Switch: switch
    Tools: tools
    TV Stand: tv-stand
    Video: video
    Virtual Host: vh 
    Virtual Machine: vm
    VLAN: vlan 
    VPN: vpn
    Windows: windows