title: Linux Tutorials
sort:
  ignore_case: true
nav:
  - configure_unattended-upgrades.md
  - svg_to_uri.md
  - unlock_luks_tpm2.md
  - define_bash_aliases.md
  - my_bash_aliases.md
  - "*"
  - tags.md