services:
  glance:
    container_name: glance
    image: panonim/dynacat:latest  # (7)!
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro  # (1)!
    ports:
      - 8580:8580
    env_file: .env  # (2)!
    labels:
      glance.name: Glance
      glance.icon: si:glance
      glance.url: http://pi-server.internal:8580
      glance.description: Server Dashboard
      glance.id: glance
    dns:   # (3)!
      - 192.168.50.2
      - 192.168.50.6
  f1_api:
    container_name: f1_api
    image: skyallinott/f1_api:latest
    environment:
      - TIMEZONE=America/New_York  # (4)!
      - TRACK_COLOUR=#B0B0B0  # (5)!
      - EVENT_DETAIL=main  # (6)!
    ports:
      - 4463:4463
    restart: unless-stopped
    dns:
      - 192.168.50.2
      - 192.168.50.6
networks: {}