services:
  yt-dlp-webui:
    image: marcobaobao/yt-dlp-webui:latest
    ports:
      - 3033:3033
    volumes:
      - /DATA/Downloads/yt-dlp:/downloads  # (1)!
      - /DATA/AppData/dockge/stacks/yt-dlp-webui/config:/config  # (2)!
    environment:
      - JWT_SECRET=your-secret
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:3033 || exit 1
